In [ ]:
import numpy as np

In [ ]:
# 1. numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Return evenly spaced values within a given interval.
np.arange(3,7,0.4)

array([3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8, 6.2, 6.6])

In [ ]:
# 2. numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
# Create an array
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
# 3. numpy.zeros(shape, dtype=float, order='C', *, like=None)
# Return a new array of given shape and type, filled with zeros.
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
# 4. numpy.ones(shape, dtype=None, order='C', *, like=None)
# Return a new array of given shape and type, filled with ones.
np.ones((2, 1))

array([[1.],
       [1.]])

In [ ]:
# 5. numpy.empty(shape, dtype=float, order='C', *, like=None)
# Return a new array of given shape and type, without initializing entries.
np.empty([2, 2])

array([[0.08703704, 0.81349206],
       [1.69312169, 0.03968254]])

In [ ]:
# 6. numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
# Return evenly spaced numbers over a specified interval.
# Returns num evenly spaced samples, calculated over the interval [start, stop].
# The endpoint of the interval can optionally be excluded.
np.linspace(0, 10, 8, endpoint=True)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [ ]:
# 7. numpy.reshape(a, newshape, order='C')
# Gives a new shape to an array without changing its data.
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 8. numpy.transpose(a, axes=None)[source]
# Returns an array with axes transposed.
a = np.array([[1, 2], [3, 4]])
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [ ]:
# 9. numpy.ravel(a, order='C')[source]
# Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 10. numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
# Join a sequence of arrays along an existing axis.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 11. numpy.vstack(tup, *, dtype=None, casting='same_kind')
# Stack arrays in sequence vertically (row wise).
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 12. numpy.hstack(tup, *, dtype=None, casting='same_kind')
# Stack arrays in sequence horizontally (column wise).
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 13. numpy.split(ary, indices_or_sections, axis=0)[source]
# Split an array into multiple sub-arrays as views into ary
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
# 14. numpy.copy(a, order='K', subok=False)[source]
# Return an array copy of the given object.
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
# Note that, when we modify x, y changes, but not z:
x[0] = 10
print(x[0] == y[0], x[0] == z[0])

True False


In [ ]:
# 15. ndarray.fill(value)
# Fill the array with a scalar value.
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [ ]:
# 16. numpy.where(condition, [x, y, ]/)
# Return elements chosen from x or y depending on .
a = np.arange(10)
print(a)
np.where(a < 5, a, 10*a)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
# 17. numpy.sort(a, axis=-1, kind=None, order=None)
# Return a sorted copy of an array
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
np.sort(a, order='height')   

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [ ]:
# 18. numpy.argsort(a, axis=-1, kind=None, order=None)
# Returns the indices that would sort an array.
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [ ]:
# 19. numpy.maximum(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'maximum'>
# Element-wise maximum of array elements.
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [ ]:
# 20. numpy.minimum(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'minimum'>
# Element-wise minimum of array elements.
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [ ]:
# 21. numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
# Return the minimum of an array or minimum along an axis.
a = np.arange(4).reshape((2,2))
print(a)
print(np.amin(a))  # Minimum of the flattened array
print(np.amin(a, axis=0))  # Minima along the first axis
print(np.amin(a, axis=1))  # Minima along the second axis

[[0 1]
 [2 3]]
0
[0 1]
[0 2]


In [ ]:
# 22. numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
# Compute the arithmetic mean along the specified axis.
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [ ]:
# 23. numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
# Compute the median along the specified axis.
a = np.array([[10, 7, 4], [3, 2, 1]])
np.median(a)

3.5

In [ ]:
# 24. numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the standard deviation along the specified axis.
# Returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, otherwise over the specified axis.
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

In [ ]:
# 25. numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the variance along the specified axis.
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

In [ ]:
# 26. numpy.dot(a, b, out=None)
# Dot product of two arrays.
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [ ]:
# 27. numpy.outer(a, b, out=None)
# Compute the outer product of two vectors.
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [ ]:
# 28. numpy.inner(a, b, /)
# Inner product of two arrays.
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [ ]:
# 29. numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
# Return the cross product of two (arrays of) vectors
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [ ]:
# 30. numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
np.trace(np.ones((3, 3)))

3.0

In [ ]:
# 31. numpy.diag(v, k=0)
# Extract a diagonal or construct a diagonal array
x = np.arange(9).reshape((3,3))
np.diag(x)

array([0, 4, 8])

In [ ]:
# 32. numpy.clip(a, a_min, a_max, out=None, **kwargs)
# Clip (limit) the values in an array.
a = np.arange(10)
print(a)
np.clip(a, 1, 8)

[0 1 2 3 4 5 6 7 8 9]


array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [ ]:
# 33. numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)[source]
# Test whether all array elements along a given axis evaluate to True.
np.all([[True,False],[True,True]])

False

In [ ]:
# 34. numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)[source]
# Test whether any array element along a given axis evaluates to True.
np.any([[True, False], [True, True]])

True

In [ ]:
# 35. numpy.isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)[source]
# Calculates element in test_elements, broadcasting over element only. Returns a boolean array of the same shape as element that is True where an element of element is in test_elements and False otherwise.
element = 2*np.arange(4).reshape((2, 2))
print(element)
test_elements = [1, 2, 4, 8]
mask = np.isin(element, test_elements)
print(mask)
print(element[mask])

[[0 2]
 [4 6]]
[[False  True]
 [ True False]]
[2 4]


In [ ]:
# 36. random.rand(d0, d1, ..., dn)
# Random values in a given shape.
np.random.rand(3,2)

array([[0.5379748 , 0.92602985],
       [0.73769899, 0.03233598],
       [0.6949513 , 0.28497316]])

In [ ]:
# 37. random.randn(d0, d1, ..., dn)
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn(2, 4)

array([[ 0.42623153, -1.44131956,  1.30705775, -0.28537534],
       [ 1.23036697,  0.2912149 , -0.9138312 , -0.10220807]])

In [ ]:
# 38. random.random_sample(size=None)
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random_sample()

0.38397177281513506

In [ ]:
# 39. random.randint(low, high=None, size=None, dtype=int)
# Return random integers from low (inclusive) to high (exclusive).
# Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low)
np.random.randint(2, size=10)

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [ ]:
# 40. random.shuffle(x)
# Modify a sequence in-place by shuffling its contents.
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 41. random.choice(a, size=None, replace=True, p=None)
# Generates a random sample from a given 1-D array
np.random.choice(5, 3)

array([0, 2, 2])

In [ ]:
# 42. random.permutation(x)
# Randomly permute a sequence, or return a permuted range.
# If x is a multi-dimensional array, it is only shuffled along its first index.
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [ ]:
# 43. fft.fft(a, n=None, axis=-1, norm=None)
# Compute the one-dimensional discrete Fourier Transform.
# This function computes the one-dimensional n-point discrete Fourier Transform (DFT) with the efficient Fast Fourier Transform (FFT) algorithm [CT].
import matplotlib.pyplot as plt
t = np.arange(256)
sp = np.fft.fft(np.sin(t))
freq = np.fft.fftfreq(t.shape[-1])
plt.plot(freq, sp.real, freq, sp.imag)
plt.show()

In [ ]:
# 44. fft.ifft(a, n=None, axis=-1, norm=None)
# Compute the one-dimensional inverse discrete Fourier Transform.
import matplotlib.pyplot as plt
t = np.arange(400)
n = np.zeros((400,), dtype=complex)
n[40:60] = np.exp(1j*np.random.uniform(0, 2*np.pi, (20,)))
s = np.fft.ifft(n)
plt.plot(t, s.real, label='real')
plt.plot(t, s.imag, '--', label='imaginary')
plt.legend()
plt.show()

In [ ]:
# 45. fft.fftshift(x, axes=None)
# Shift the zero-frequency component to the center of the spectrum.
freqs = np.fft.fftfreq(10, 0.1)
freqs

array([ 0.,  1.,  2.,  3.,  4., -5., -4., -3., -2., -1.])

In [ ]:
# 46. fft.ifftshift(x, axes=None)
# The inverse of fftshift. Although identical for even-length x, the functions differ by one sample for odd-length x.\
freqs = np.fft.fftfreq(9, d=1./9).reshape(3, 3)
print(freqs)
np.fft.ifftshift(np.fft.fftshift(freqs))

[[ 0.  1.  2.]
 [ 3.  4. -4.]
 [-3. -2. -1.]]


array([[ 0.,  1.,  2.],
       [ 3.,  4., -4.],
       [-3., -2., -1.]])

In [ ]:
# 47. fft.fftfreq(n, d=1.0)
# Return the Discrete Fourier Transform sample frequencies.
# The returned float array f contains the frequency bin centers in cycles per unit of the sample spacing (with zero at the start). For instance, if the sample spacing is in seconds, then the frequency unit is cycles/second.
signal = np.array([-2, 8, 6, 4, 1, 0, 3, 5], dtype=float)
fourier = np.fft.fft(signal)
n = signal.size
timestep = 0.1
freq = np.fft.fftfreq(n, d=timestep)
freq

array([ 0.  ,  1.25,  2.5 ,  3.75, -5.  , -3.75, -2.5 , -1.25])

In [ ]:
# 48. fft.rfft(a, n=None, axis=-1, norm=None)
# Compute the one-dimensional discrete Fourier Transform for real input.
# This function computes the one-dimensional n-point discrete Fourier Transform (DFT) of a real-valued array by means of an efficient algorithm called the Fast Fourier Transform (FFT).
print(np.fft.fft([0, 1, 0, 0]))
print(np.fft.rfft([0, 1, 0, 0]))

[ 1.+0.j  0.-1.j -1.+0.j  0.+1.j]
[ 1.+0.j  0.-1.j -1.+0.j]


In [ ]:
# 49. fft.irfft(a, n=None, axis=-1, norm=None)
# Computes the inverse of rfft.
# This function computes the inverse of the one-dimensional n-point discrete Fourier Transform of real input computed by rfft. In other words, irfft(rfft(a), len(a)) == a to within numerical accuracy. (See Notes below for why len(a) is necessary here.)
print(np.fft.ifft([1, -1j, -1, 1j]))
print(np.fft.irfft([1, -1j, -1]))

[0.+0.j 1.+0.j 0.+0.j 0.+0.j]
[0. 1. 0. 0.]


In [ ]:
# 50. numpy.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)
# Least squares polynomial fit.
import warnings
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 3)
z

array([ 0.08703704, -0.81349206,  1.69312169, -0.03968254])